### ISSUE TITLE
Class-agnostic char interface?

### ISSUE THREAD

**Issue by ninnghazad** [earthiverse/ALClient#12]
is there a single interface for all classes that one could use? i don't want to duplicate code on migration for different classes. atm it's just one code for all chars.

EDIT: just saw hardcoded skills per class - so probably not.

**Comment by earthiverse** [comment]
Yeah, I set it up that way to make sure you don't try to call `blink` on a warrior, for example.
You technically can call `new PingCompensatedCharacter()` if you don't need to use any class specific skills, but that's kind of silly.
