### ISSUE TITLE
ReferenceError: exports is not defined in ES module scope

### ISSUE THREAD

**Issue by Noitabara** [earthiverse/ALClient#13]
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'C:\Users\user\Documents\alclient-test\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

 "esModuleInterop": true is set.
"type": "module" is set.
node version 16.13.2- though I tried on 16.5 and 17 as well.

**Comment by earthiverse** [comment]
I feel like it might be a config issue with your tsconfig.json.

Do you mind sharing the folder structure of your project, and your tsconfig.json?

**Comment by Noitabara** [comment]
> I feel like it might be a config issue with your tsconfig.json.
> 
> Do you mind sharing the folder structure of your project, and your tsconfig.json?

No problem;
tsconfig.json-
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs", 
    "strict": true, 
    "esModuleInterop": true,    
    "skipLibCheck": true, 
    "forceConsistentCasingInFileNames": true
  }
}
`
folder structure
![Code_-_Insiders_tx0DE65Jwe](https://user-images.githubusercontent.com/5560528/150121500-3af4e747-d0a8-4a8c-b0a7-ab2d66085624.png)

**Comment by Noitabara** [comment]
Got it working- pulled down your tsconfig from another project and stopped trying to get ts-node-dev to work and we're good to go. Will look into the issues with ts-node-dev later though honestly- developing that way given what is developed probably isn't the best use case for that package. Thanks!

**Comment by earthiverse** [comment]
Running in `ts-node` should be OK. I think that's how the tests run when I build the project before publishing.

Your issue may have been related to not having an "include" filter to only compile .ts files.
```json
    "include": [
        "source/**/*.ts",
        "source/definitions/bot.ts"
    ],
```

**Comment by Noitabara** [comment]
I think so as well- and I haven't tried ts-node, only ts-node-dev. Will give both a shot after i'm done porting over some functionality haha. Thanks again!
