### ISSUE TITLE
Can't run sample script

### ISSUE THREAD

**Issue by Ciechom** [earthiverse/ALClient#3]
That's the error I'm getting while trying to run sample code from README.

`PS J:\ALC> npx tsc main.ts
main.ts:1:8 - error TS1192: Module '"J:/ALC/node_modules/alclient/build/index"' has no default export.

1 import AL from "alclient"
         ~~

node_modules/alclient/build/Pathfinder.d.ts:2:8 - error TS1192: Module '"J:/ALC/node_modules/ngraph.path/index"' has no default export.

2 import path from "ngraph.path";
         ~~~~


Found 2 errors.`

My sample code:
`import AL from "alclient"

async function run() {
    await Promise.all([AL.Game.loginJSONFile("../credentials.json"), AL.Game.getGData()])
    await AL.Pathfinder.prepare(AL.Game.G)

    const merchant = await AL.Game.startMerchant("Seler", "ASIA", "I")
    console.log("Moving to main")
    await merchant.smartMove("main")
    console.log("Moving to cyberland")
    await merchant.smartMove("cyberland")
    console.log("Moving to halloween")
    await merchant.smartMove("halloween")

    merchant.disconnect()
}
run()`

**Comment by earthiverse** [comment]
Try running `npx tsc --esModuleInterop main.ts`.
If you have a `tsconfig.json` file, you can set it in there, too. Take a look at [my tsconfig.json](https://github.com/earthiverse/adventureland-bots/blob/master/tsconfig.json) if you want.

**Comment by Ciechom** [comment]
That's weird when using that command you provided it did not throw any errors. But I'm using that same tsconfig.json file but maybe I have it in a wrong directory? I just cloned your git repo before doing anything so it's in the same directory that it came in. Should I move it somwhere? It's now in the same directory that main.ts is in.

How can I run the script after it was compiled?

Sorry for the dumb questions :)

**Comment by earthiverse** [comment]
Try running `npx tsc` with no additional arguments.

**Comment by Ciechom** [comment]
Ok, everything was a mess in my files.

What worked:
`npx tsc` when `main.ts` was in source folder
then from cmd from build folder running: `node main.js`

I did some digging on `tsconfig.json` and when you give `npx tsc`  an input file it ignores `tsconfig.json`
